package com.litingzhe.justandroid.netdb.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.litingzhe.justandroid.netdb.db.model.BoxCode;
import com.litingzhe.justandroid.netdb.db.model.Land;

import com.litingzhe.justandroid.netdb.db.dao.BoxCodeDao;
import com.litingzhe.justandroid.netdb.db.dao.LandDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boxCodeDaoConfig;
    private final DaoConfig landDaoConfig;

    private final BoxCodeDao boxCodeDao;
    private final LandDao landDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boxCodeDaoConfig = daoConfigMap.get(BoxCodeDao.class).clone();
        boxCodeDaoConfig.initIdentityScope(type);

        landDaoConfig = daoConfigMap.get(LandDao.class).clone();
        landDaoConfig.initIdentityScope(type);

        boxCodeDao = new BoxCodeDao(boxCodeDaoConfig, this);
        landDao = new LandDao(landDaoConfig, this);

        registerDao(BoxCode.class, boxCodeDao);
        registerDao(Land.class, landDao);
    }
    
    public void clear() {
        boxCodeDaoConfig.clearIdentityScope();
        landDaoConfig.clearIdentityScope();
    }

    public BoxCodeDao getBoxCodeDao() {
        return boxCodeDao;
    }

    public LandDao getLandDao() {
        return landDao;
    }

}
